Repository BudgetBuddiesTeam/FrontEnd, pull requests merged in 2024-08, with the labels that each got.

#49 [Feat] 캘린더 위에 RaisedView올리기 구현
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/CategorySelectTableViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/DefaultCategory.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/BottomSheet/Controllers/BottomSheetViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/CustomInfoColor.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/InfoTitleWithButtonCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/InformationCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/MainCalendarCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/RaisedInfoView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/TempModel.swift
Labels: feature

#52 [Chore] xcconfig 파일에 네트워크을 위한 config 파일 준비 #51
  .gitignore
  BudgetBuddies/Project.swift
Labels: chore

#60 [Chore] BASE URL 세팅 #59
  BudgetBuddies/BudgetBuddies/Sources/Network/ServerInfo.swift
  BudgetBuddies/Project.swift
  BudgetBuddies/Tuist/Package.resolved
  BudgetBuddies/Tuist/Package.swift
Labels: Chore

#62 [Feat] HTTP 서버 통신을 위한 기초 설정 #61
  BudgetBuddies/BudgetBuddies/Sources/Network/AccountBook/DTO/CategoryRequest.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/AccountBook/DTO/CategoryResponse.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/AccountBook/Router/CategoryRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategoryPlus/CategoryPlusViewController.swift
  BudgetBuddies/Project.swift
Labels: Feature

#70 [Feat] 메인화면 UI 구현
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/Lemon.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/Lemon2.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/Lemon3.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/MainBox.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/MainBoxStroke.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/Orange2.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/Sky3.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/Sky4.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/StrokeGray1.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/MainViewImage/ChartIcon.imageset/ChartIcon.svg
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/MainViewImage/ChartIcon.imageset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/MainViewImage/CommentBox.imageset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/MainViewImage/CommentBox.imageset/Union.svg
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/MainViewImage/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/MainViewImage/GraphIcon.imageset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/MainViewImage/GraphIcon.imageset/graph ic1.svg
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/MainViewImage/ZigZagSampleIcon.imageset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/MainViewImage/ZigZagSampleIcon.imageset/unnamed 1.pdf
  BudgetBuddies/BudgetBuddies/Sources/Extensions/UILabel+.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/AccountBook/DTO/CategoryRequest.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/AccountBook/DTO/CategoryResponse.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/AccountBook/Router/CategoryRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/RootTabBarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategoryPlus/CategoryPlusViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewUIComponents/CoreYellowBackground.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewUIComponents/HomeTextLabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewUIComponents/MonthlyBudgetInfoCollectionView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewUIComponents/MonthlyBudgetInfoCollectionViewUIComponents/MonthlyBudgetInfoCollectionViewCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewUIComponents/MonthlyBudgetInfoCollectionViewUIComponents/MonthlyBudgetInfoCollectionViewFlowLayout.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewUIComponents/MonthlyBudgetInfoTextLabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewUIComponents/MonthlyConsumedAnalysisFirstItem.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewUIComponents/MonthlyConsumedAnalysisSecondItem.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewUIComponents/MonthlyConsumedAnalysisTextLabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewUIComponents/SummaryInfoContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewUIComponents/SummaryInfoContainerViewUIComponents/LeftMoneyContainer.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewUIComponents/SummaryInfoContainerViewUIComponents/LeftPriceUILabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewUIComponents/TextAndRightChevronButtonContainer.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/ViewControllers/ConsumeReportViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/ViewControllers/GoalReportViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/ViewControllers/MonthReportViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/Views/FaceChartView.swift
  BudgetBuddies/Project.swift
  BudgetBuddies/Tuist/Package.swift
Labels: Feature

#74 [Feat] 캘린더 전체보기 api 연결
  BudgetBuddies/BudgetBuddies/Sources/Network/Calendar/DTO/CalendarResponse.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/Calendar/DTO/DiscountsResponse.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/Calendar/DTO/SupportsResponse.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/Calendar/NetworkManager/CalendarManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/Calendar/NetworkManager/DiscountInfoManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/Calendar/NetworkManager/SupportInfoManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/Calendar/Router/CalendarRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/Calendar/Router/DiscountInfoRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/Calendar/Router/InfoRequest.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/Calendar/Router/SupportInfoRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Helpers/AlertManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Models/InfoType.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Models/TempModel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Models/YearMonth.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/InformationCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/MainCalendarCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/InfoList/Controllers/InfoListViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/MonthPicker/Controllers/MonthPickerViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/MonthPicker/Views/MonthPicker.swift
Labels: Feature

#78 [Feat] 메인화면에서 다른 View로 연결되는 로직 설계 #76
  BudgetBuddies/BudgetBuddies/Sources/RootTabBarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewUIComponents/SummaryInfoContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewUIComponents/TextAndRightChevronButton.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/ViewControllers/AnalysisReportViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/ViewControllers/ConsumeReportViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/ViewControllers/GoalReportViewController.swift
Labels: Feature

#91 [Feat] 전체보기 페이지 내부 로직 설계 #90
  BudgetBuddies/BudgetBuddies/Sources/Network/CategoryController/Router/CategoryRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/ExpenseController/DTO/AddedExpenseRequestDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/ExpenseController/DTO/MonthlyExpenseResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/ExpenseController/DTO/UpdatedExpenseRequestDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/ExpenseController/Router/ExpenseRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategoryPlus/CategoryPlusView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategoryPlus/CategoryPlusViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/CategorySelectTableViewCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/CategorySelectTableViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryHeaderView/ConsumedHIstoryHearderViewUIComponents/ConsumedPriceUILabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryHeaderView/ConsumedHIstoryHearderViewUIComponents/CurrentMonthUILabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryHeaderView/ConsumedHistoryHeaderView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryTableViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistoryDetail/ConsumedHistoryDetailView/ConsumedHIstoryDetailViewUIComponents/PriceUILabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistoryDetail/ConsumedHistoryDetailView/ConsumedHistoryDetailView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistoryDetail/ConsumedHistoryDetailViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingView/AllLookingView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingView/AllLookingViewUIComponents/AllServiceContainerView/AllServiceContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingView/AllLookingViewUIComponents/AnalysisContainerView/AnalysisContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingView/AllLookingViewUIComponents/ProflieContainerView/ProfileContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/ProfileEditView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/ProfileEditViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/SubView/ProfileEditViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/ViewControllers/MonthReportViewController.swift
  BudgetBuddies/Project.swift
  BudgetBuddies/Tuist/Package.swift
Labels: Feature, Refactor

#92 [Feat] 메인페이지 내부 로직 설계 #72
  BudgetBuddies/BudgetBuddies/Sources/Network/MainPageController/DTO/APIResponseMainPageResponseDto.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/MainPageController/DTO/ConsumpotionGoalResponseListDto.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/MainPageController/DTO/ConsumptionAnalysisResponseDto.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/MainPageController/DTO/MainPageResponseDto.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/MainPageController/DTO/TopGoalCategoryResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/MonthlyBudgetInfoCollectionView/MonthlyBudgetInfoCollectionViewUIComponents/MonthlyBudgetInfoCollectionViewCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/SummaryInfoContainerView/SummaryInfoContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/SummaryInfoContainerView/SummaryInfoContainerViewUIComponents/CategoryLeftMoneyContainer.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/SummaryInfoContainerView/SummaryInfoContainerViewUIComponents/CommentTextLabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/SummaryInfoContainerView/SummaryInfoContainerViewUIComponents/LeftMoneyContainerUIComponents/LeftPriceUILabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/SummaryInfoContainerView/SummaryInfoContainerViewUIComponents/MainTextLabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/ViewControllers/GoalEditViewController.swift
Labels: Feature, Refactor

#100 [Feat & Refactor]캘린더 메인 테이블뷰 수정사항 반영
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/readyInfoImage.imageset/Image.png
  BudgetBuddies/BudgetBuddies/Sources/Network/Calendar/DTO/CalendarResponse.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/Calendar/DTO/DiscountsResponse.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/Calendar/DTO/SupportsResponse.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Cells/InformationCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Cells/ReadyInfoCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/CalendarView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/CalendarViewUIComponents/InfoTitleWithButtonView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/InfoList/Controllers/InfoListViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/MonthlyBudgetInfoCollectionView/MonthlyBudgetInfoCollectionViewUIComponents/MonthlyBudgetInfoCollectionViewCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/SummaryInfoContainerView/SummaryInfoContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/SummaryInfoContainerView/SummaryInfoContainerViewUIComponents/CategoryLeftMoneyContainer.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/SummaryInfoContainerView/SummaryInfoContainerViewUIComponents/CommentTextLabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/SummaryInfoContainerView/SummaryInfoContainerViewUIComponents/LeftMoneyContainerUIComponents/LeftPriceUILabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/SummaryInfoContainerView/SummaryInfoContainerViewUIComponents/MainTextLabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewController.swift
Labels: Feature, Refactor

#103 [Chore] TuistPracticeTests 파일 제거 #102
  BudgetBuddies/BudgetBuddies/Tests/TuistPracticeTests.swift
Labels: Chore

#104 [Feat] 캘린더 api 연결
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Models/TempModel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/CalendarViewUIComponents/MainCalendarView.swift
Labels: Feature

#106 [Bug fix] 캘린더 제약조건 겹치는 문제 해결
  BudgetBuddies/BudgetBuddies/Sources/Network/CalendarController/DTO/CalendarResponse.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CalendarController/DTO/DiscountsResponse.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CalendarController/DTO/SupportsResponse.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CalendarController/NetworkManager/CalendarManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CalendarController/NetworkManager/DiscountInfoManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CalendarController/NetworkManager/SupportInfoManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CalendarController/Router/CalendarRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CalendarController/Router/DiscountInfoRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CalendarController/Router/InfoRequest.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CalendarController/Router/SupportInfoRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Models/RaisedInfoModel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/CalendarViewUIComponents/MainCalendarView.swift
Labels: BugFix, Chore

#107 [Feat]MainViewController -> InfoListViewController 이동 구현
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Models/YearMonth.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/InfoList/Controllers/InfoListViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/MonthlyBudgetInfoCollectionView/MonthlyBudgetInfoCollectionViewUIComponents/MonthlyBudgetInfoCollectionViewCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewController.swift
Labels: 📲 Feature, 🧰 Refactor

#109 [Feat & Refactor] AllLookingVC -> InfoListVC, 주머니 캘린더(CalendarVC)로 이동하는 부분 수정
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewController.swift
Labels: 📲 Feature, 🛠️ BugFix, 🧰 Refactor

#111 [Feat] 댓글 api 연동 (댓글수정X)
  BudgetBuddies/BudgetBuddies/Sources/Extensions/Encodable+.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CalendarController/DTO/CalendarResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CalendarController/NetworkManager/CalendarManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CalendarController/Requests/InfoRequest.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/DTO/DiscountsCommentsRequestDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/DTO/DiscountsCommentsResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/DTO/GetOneDiscountsCommentsResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/DTO/GetOneSupportsCommentsResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/DTO/SupportsCommentsRequestDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/DTO/SupportsCommentsResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/NetworkManager/CommentManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/Requests/CommentRequest.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/Router/CommentRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/DiscountInfoController/DTO/DiscountsResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/DiscountInfoController/NetworkManager/DiscountInfoManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/DiscountInfoController/Router/DiscountInfoRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/SupportInfoController/DTO/SupportsResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/SupportInfoController/NetwortManager/SupportInfoManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/SupportInfoController/Router/SupportInfoRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/BottomSheet/Cells/CommentCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/BottomSheet/Cells/NoCommentsCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/BottomSheet/Controllers/BottomSheetViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/BottomSheet/Views/BottomSheet.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Cells/InformationCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/CalendarViewUIComponents/MainCalendarView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Helpers/AlertManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/InfoList/Controllers/InfoListViewController.swift
Labels: 📲 Feature, 🛠️ BugFix

#115 [Feat] 커스텀 탭바
  BudgetBuddies/BudgetBuddies/BudgetBuddiesTests/ExpenseRouterTests.swift
  BudgetBuddies/BudgetBuddies/Sources/CustomTabBar/Controllers/CustomTabBarController.swift
  BudgetBuddies/BudgetBuddies/Sources/CustomTabBar/Controllers/RootTabBarController.swift
  BudgetBuddies/BudgetBuddies/Sources/CustomTabBar/Views/CustomTabBarIcon.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/Router/CommentRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/ExpenseController/DTO/ResponseDTO/CompactExpenseResponseDto.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/ExpenseController/DTO/ResponseDTO/MonthlyExpenseCompactResponseDto.swift
  BudgetBuddies/BudgetBuddies/Sources/RootTabBarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/SceneDelegate.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/CategorySelectTableViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryModel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryTableViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/ProfileEditView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/CalendarView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/InfoList/Controllers/InfoListViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/ViewControllers/AnalysisReportViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/ViewControllers/GoalEditViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/ViewControllers/MonthReportViewController.swift
Labels: 📲 Feature

#119 [Refactor] 가계부 영역에 있는 소비 내역 관련 API 비즈니스 로직 설계
  BudgetBuddies/BudgetBuddies/BudgetBuddiesTests/ExpenseRouterTests.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/ExpenseController/DTO/RequestDTO/AddedExpenseResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/ExpenseController/DTO/ResponseDTO/CompactExpenseResponseDto.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/ExpenseController/DTO/ResponseDTO/DailyExpenseResponseDto.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/ExpenseController/DTO/ResponseDTO/MonthlyExpenseCompactResponseDto.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/ExpenseController/DTO/ResponseDTO/MonthlyExpenseResponseDto.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryHeaderView/ConsumedHIstoryHearderViewUIComponents/ConsumedPriceUILabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryHeaderView/ConsumedHIstoryHearderViewUIComponents/CurrentMonthUILabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryHeaderView/ConsumedHistoryHeaderView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryModel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryTableViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistoryDetail/ConsumedHistoryDetailViewController.swift
Labels: 🧰 Refactor

#121 [Feat] 댓글 수정, 댓글 개수 api 연결
  BudgetBuddies/BudgetBuddies/Sources/Network/CalendarController/DTO/RequestDTO/InfoRequestDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CalendarController/DTO/ResponseDTO/CalendarResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/DTO/RequestDTO/DiscountsCommentsRequestDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/DTO/RequestDTO/SupportsCommentsRequestDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/DTO/ResponseDTO/DiscountsCommentsResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/DTO/ResponseDTO/GetOneDiscountsCommentsResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/DTO/ResponseDTO/GetOneSupportsCommentsResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/DTO/ResponseDTO/SupportsCommentsResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/NetworkManager/CommentManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/Requests/PostCommentRequestDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/Requests/PutCommentRequestDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/Router/CommentRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/DiscountInfoController/NetworkManager/DiscountInfoManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/DiscountInfoController/Router/DiscountInfoRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/SupportInfoController/NetwortManager/SupportInfoManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/SupportInfoController/Router/SupportInfoRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistoryDetail/ConsumedHistoryDetailViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/BottomSheet/Controllers/BottomSheetViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Cells/InformationCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/InfoList/Controllers/InfoListViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/CustomTabBar/Controllers/CustomTabBarController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/CustomTabBar/Controllers/RootTabBarController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/CustomTabBar/Views/CustomTabBarIcon.swift
Labels: 📲 Feature, 🧰 Refactor

#123 [Feat & BugFix] 댓글 오류 수정
  BudgetBuddies/BudgetBuddies/Sources/Network/CommentController/NetworkManager/CommentManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/BottomSheet/Controllers/BottomSheetViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Cells/InformationCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/CustomTabBar/Controllers/CustomTabBarController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/CustomTabBar/Views/CustomTabBarIcon.swift
Labels: 📲 Feature, 🛠️ BugFix

#125 [Refactor] TestFlight 배포용 Bundle Identifier 수정
  BudgetBuddies/Project.swift
Labels: 🧰 Refactor

#126 [Feat]좋아요 api 연동
  BudgetBuddies/BudgetBuddies/Sources/Network/DiscountInfoController/DTO/DiscountOneResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/DiscountInfoController/NetworkManager/DiscountInfoManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/DiscountInfoController/Router/DiscountInfoRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/SupportInfoController/DTO/SupportOneResponseDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/SupportInfoController/NetwortManager/SupportInfoManager.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/SupportInfoController/Router/SupportInfoRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Cells/InformationCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/InfoList/Controllers/InfoListViewController.swift
Labels: 📲 Feature

#127 [Refactor] 버그를 일으키는 앱 설정 값 수정 후 Info.plist 파일에 반영
  BudgetBuddies/Project.swift
Labels: 🧰 Refactor

#130 [Refactor] 1.1.0 버전 명시
  BudgetBuddies/Project.swift
Labels: 🧰 Refactor

#132 [Feat & Refactor] UI 수정
  BudgetBuddies/BudgetBuddies/BudgetBuddiesTests/CategoryRouterTests.swift
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/pieChartBackImage.imageset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/pieChartBackImage.imageset/Image.png
  BudgetBuddies/BudgetBuddies/Sources/Extensions/UITextField+.swift
  BudgetBuddies/BudgetBuddies/Sources/Extensions/UIView+.swift
  BudgetBuddies/BudgetBuddies/Sources/Extensions/UIViewController+.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CategoryController/Router/CategoryRouter.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategoryPlus/CategoryPlusViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/CategorySelectTableModel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/CategorySelectTableViewCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/CategorySelectTableViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryTableViewCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryTableViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistoryDetail/ConsumedHistoryDetailView/ConsumedHistoryDetailView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistoryDetail/ConsumedHistoryDetailViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingView/AllLookingView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingView/AllLookingViewUIComponents/AllServiceContainerView/AllServiceContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingView/AllLookingViewUIComponents/AnalysisContainerView/AnalysisContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingView/AllLookingViewUIComponents/ProflieContainerView/ProfileContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/ProfileEditView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/ProfileEditViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/BottomSheet/Cells/CommentCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Cells/InformationCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/CalendarViewUIComponents/BannerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/CalendarViewUIComponents/MainCalendarView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/InfoList/Controllers/InfoListViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/MonthlyBudgetInfoCollectionView/MonthlyBudgetInfoCollectionViewUIComponents/MonthlyBudgetInfoCollectionViewCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/MonthlyBudgetInfoTextLabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/MonthlyConsumedAnalysisFirstItem.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/MonthlyConsumedAnalysisSecondItem.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/MonthlyConsumedAnalysisTextLabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/SummaryInfoContainerView/SummaryInfoContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/SummaryInfoContainerView/SummaryInfoContainerViewUIComponents/CategoryLeftMoneyContainer.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/SummaryInfoContainerView/SummaryInfoContainerViewUIComponents/CommentTextLabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/TextAndRightChevronButton.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/Cells/ReportTableViewCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/ViewControllers/AgeEditViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/ViewControllers/AnalysisReportViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/ViewControllers/ConsumeReportViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/ViewControllers/GoalReportViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/Views/GoalChartView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/Views/ReportBarChartView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/Views/TopStackView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/ViewControllers/GoalEditViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/ViewControllers/GoalTotalViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/ViewControllers/MonthReportViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/Views/Cells/AccountBookCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/Views/Cells/SpendGoalCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/Views/FaceChartView.swift
  BudgetBuddies/Project.swift
Labels: 📲 Feature, 🧰 Refactor

#134 [BugFix] 카테고리 선택 후 소비 추가하기 화면에 선택한 카테고리로 반영이 안되는 문제 #133
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeView.swift
Labels: 🛠️ BugFix

#136 [Refactor] 소비추가 컨트롤러에서 소비 추가 후 모든 필드값 초기화
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeViewController.swift
Labels: 🧰 Refactor

#139 [Refactor] 빈주머니즈 앱 아이콘 수정 #138
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 🧰 Refactor

#141 [Refactor] 메인화면 데이터가 로딩되는 시간 연장하는 UX 설계 #140
  BudgetBuddies/BudgetBuddies/Sources/SceneDelegate.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/CustomTabBar/Controllers/RootTabBarController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/ExtendedLaunchScreen/ExtendedLaunchScreenView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/ExtendedLaunchScreen/ExtendedLaunchScreenViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewController.swift
Labels: 🧰 Refactor

#143 [Refactor] 빈주머니즈 사용 국가 변경 #142
  BudgetBuddies/BudgetBuddies/Resources/ko.lproj/LaunchScreen.strings
  BudgetBuddies/Project.swift
Labels: 🧰 Refactor

#144 [Refactor]메인뷰 상단 노란 뷰 수정 및 추가 UI수정
  BudgetBuddies/BudgetBuddies/Sources/Extensions/UITextField+.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategoryPlus/CategoryPlusView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategoryPlus/CategoryPlusViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/CategorySelectTableViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/ProfileEditView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/ProfileEditViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/InfoList/Controllers/InfoListViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/ViewControllers/AnalysisReportViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/ViewControllers/ConsumeReportViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/ViewControllers/GoalReportViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/ViewControllers/GoalEditViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/ViewControllers/GoalTotalViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/ViewControllers/MonthReportViewController.swift
  BudgetBuddies/Project.swift
Labels: 🧰 Refactor

#146 [Refactor] 텍스트필드 프롬프트 설정
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/ProfileEditView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/ViewControllers/GoalEditViewController.swift
Labels: 🧰 Refactor

#148 [Refactor] 카테고리 신규 추가 시 목록에 업데이트 #147
  BudgetBuddies/BudgetBuddies/BudgetBuddiesTests/CategoryRouterTests.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/CategoryController/DTO/CategoryRequestDTO.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategoryPlus/CategoryPlusViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/CategorySelectTableViewController.swift
Labels: 🧰 Refactor

#149 [Refactor] 1.2.0 배포를 위한 버전 입력
  BudgetBuddies/Project.swift
Labels: 🧰 Refactor

#153 [BugFix] 데모데이때 발생한 버그 수정
  BudgetBuddies/BudgetBuddies/Sources/Extensions/UIViewController+.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategoryPlus/CategoryPlusViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/MonthlyConsumedAnalysisFirstItem.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/MonthlyConsumedAnalysisSecondItem.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/ViewControllers/AgeEditViewController.swift
Labels: 🛠️ BugFix

#154 [Chore] 이슈 템플릿 업데이트
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bugfix.md
  .github/ISSUE_TEMPLATE/new-feature-task.md
  .github/ISSUE_TEMPLATE/refactoring-request.md
Labels: 🗂️ Chore

#157 [Refactor] MainController에 해당하는 비즈니스 로직을 MainModel로 관심사 분리
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/new-feature-task.md
  .github/ISSUE_TEMPLATE/refactoring-request.md
  BudgetBuddies/BudgetBuddies/BudgetBuddiesTests/MainRouterTests.swift
  BudgetBuddies/BudgetBuddies/Sources/Network/MainPageController/DTO/ApiResponseMainPageResponseDto.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/CustomTabBar/Controllers/RootTabBarController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/ExtendedLaunchScreen/ExtendedLaunchScreenViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainModel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainView/MainViewUIComponents/SummaryInfoContainerView/SummaryInfoContainerViewUIComponents/CommentTextLabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewController.swift
Labels: 🧰 Refactor

#159 Refactor/158 main view user name refactoring
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewController.swift
Labels: 🧰 Refactor

#160 [Chore] 1.2.1 버전으로 지정
  BudgetBuddies/Project.swift
Labels: 🗂️ Chore
