Repository BudgetBuddiesTeam/FrontEnd, pull requests merged in 2024-07, with the labels that each got.

#6 [Chore] 프리텐다드 폰트 추가
  BudgetBuddies/BudgetBuddies/Resources/PretendardFont/Pretendard-Black.otf
  BudgetBuddies/BudgetBuddies/Resources/PretendardFont/Pretendard-Bold.otf
  BudgetBuddies/BudgetBuddies/Resources/PretendardFont/Pretendard-ExtraBold.otf
  BudgetBuddies/BudgetBuddies/Resources/PretendardFont/Pretendard-ExtraLight.otf
  BudgetBuddies/BudgetBuddies/Resources/PretendardFont/Pretendard-Light.otf
  BudgetBuddies/BudgetBuddies/Resources/PretendardFont/Pretendard-Medium.otf
  BudgetBuddies/BudgetBuddies/Resources/PretendardFont/Pretendard-Regular.otf
  BudgetBuddies/BudgetBuddies/Resources/PretendardFont/Pretendard-SemiBold.otf
  BudgetBuddies/BudgetBuddies/Resources/PretendardFont/Pretendard-Thin.otf
Labels: chore

#7 [Chore] TabBarController 파일 추가 & SceneDelegate에서 루트뷰로 설정 & 코드포맷터로 변경 정리된 파일 추가
  BudgetBuddies/BudgetBuddies/Sources/AppDelegate.swift
  BudgetBuddies/BudgetBuddies/Sources/RootTabBarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/SceneDelegate.swift
  BudgetBuddies/BudgetBuddies/Sources/ViewController.swift
  BudgetBuddies/BudgetBuddies/Tests/TuistPracticeTests.swift
  BudgetBuddies/Project.swift
  BudgetBuddies/Tuist/Package.swift
Labels: chore

#10 [Feat & Chore] 7월 24일자 작업사항 업로드
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/Background.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/BarGray.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/CalendarBlue.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/CalendarYellow.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/CircleStroke.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/CoreBlue.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/Face.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/GrayButton.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/Heart.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/LogoLine1.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/LogoLine2.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/SubBlue.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/SubGray.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/TextBlack.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/TextBox.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/TextExample.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/coreYellow.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/DesignSystem/HexColorCodeString.swift
  BudgetBuddies/BudgetBuddies/Resources/DesignSystem/PretendardFont.swift
  BudgetBuddies/BudgetBuddies/Sources/Extensions/UIView+.swift
  BudgetBuddies/BudgetBuddies/Sources/RootTabBarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategoryPlus/CategoryPlus.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategoryPlus/CategoryPlusViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/CategorySelectTableViewCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/CategorySelectTableViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/Consume.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeViewController.swift
  BudgetBuddies/BudgetBuddies/Support/InfoPlists/BudgetBuddies-Info.plist
Labels: feature, chore

#12 [Chore] Project에서 Info.plist 코드 복구 & Info.plist 파일에 폰트 추가
  BudgetBuddies/BudgetBuddies/Resources/InfoPlists/BudgetBuddies-Info.plist
  BudgetBuddies/Project.swift
Labels: chore

#17 [Feat] 7월 24일자 각자 담당한 화면 병합 코드
  BudgetBuddies/BudgetBuddies/Sources/RootTabBarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategoryPlus/CategoryPlus.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/CategorySelectTableViewCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/Consume.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/ViewControllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/ViewControllers/DetailViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/ViewControllers/MonthPickerPopUp/DimmedViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/ViewControllers/MonthPickerPopUp/MonthPickerViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/ViewControllers/WebViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Views/CalendarImageCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Views/CustomInfoColorView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Views/InfoTitleCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Views/InformationCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Views/MainCalendarCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Views/MonthPickerCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Main/MainViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/AnalysisReportViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/GoalChartView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/AnalysisReport/TopStackView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/FaceChartView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Report/MonthReport/MonthReportViewController.swift
  BudgetBuddies/Project.swift
  BudgetBuddies/Tuist/Package.swift
Labels: feature

#19 [Chore] 7월 24일 회의 후 필요하다고 생각되는 후속 조치 #18
  BudgetBuddies/BudgetBuddies/Info.plist
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppColor/White.colorset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/DesignSystem/HexColorCodeString.swift
  BudgetBuddies/BudgetBuddies/Resources/DesignSystem/PretendardFont.swift
  BudgetBuddies/BudgetBuddies/Resources/InfoPlists/BudgetBuddies-Info.plist
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategoryPlus/CategoryPlus.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/CategorySelectTableViewCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/Consume.swift
Labels: chore

#22 [Chore] [Chore] 이슈, PR 템플릿 수정 #21
  .github/ISSUE_TEMPLATE/bugfix.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/pull_request_template.md
Labels: chore

#29 [Feat] 가계부 페이지 구현 #25
  BudgetBuddies/BudgetBuddies/Sources/Extensions/UIButton+.swift
  BudgetBuddies/BudgetBuddies/Sources/Extensions/UILabel+.swift
  BudgetBuddies/BudgetBuddies/Sources/Extensions/UITextField+.swift
  BudgetBuddies/BudgetBuddies/Sources/Extensions/UITextView+.swift
  BudgetBuddies/BudgetBuddies/Sources/Extensions/UIView+.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryHeaderView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryTableViewCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryTableViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistoryDetail/ConsumedHistoryDetailView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistoryDetail/ConsumedHistoryDetailViewController.swift
Labels: feature

#32 [Feat] 캘린더 페이지 전체보기 구현
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryTableViewCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryTableViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/InfoTitleWithButtonCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/InfoList/Controllers/InfoListViewController.swift
Labels: feature

#34 [Feat] 캘린더 페이지 InformationCell 기능 구현
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/fillHeartIconImage.imageset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/fillHeartIconImage.imageset/Image.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/sendButtonImage.imageset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/sendButtonImage.imageset/Image.png
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/BottomSheet/Controllers/BottomSheetViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/BottomSheet/Controllers/DimmedViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/BottomSheet/Views/BottomSheet.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/BannerCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/CustomInfoColor.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/InfoTitleWithButtonCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/InformationCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/MainCalendarCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/InfoList/Controllers/InfoListViewController.swift
Labels: feature

#37 [Feat] 전체보기 페이지 구현 #36
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/IconForAllLookingView/AllServiceContainer/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/IconForAllLookingView/AllServiceContainer/Lightning.imageset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/IconForAllLookingView/AllServiceContainer/Lightning.imageset/Image.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/IconForAllLookingView/AllServiceContainer/QuestionMarkCircle.imageset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/IconForAllLookingView/AllServiceContainer/QuestionMarkCircle.imageset/Image.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/IconForAllLookingView/AllServiceContainer/TodayCalendar.imageset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/IconForAllLookingView/AllServiceContainer/TodayCalendar.imageset/Image.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/IconForAllLookingView/AnalysisContainer/Analysis.imageset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/IconForAllLookingView/AnalysisContainer/Analysis.imageset/Image.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/IconForAllLookingView/AnalysisContainer/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/IconForAllLookingView/AnalysisContainer/DeclineChart.imageset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/IconForAllLookingView/AnalysisContainer/DeclineChart.imageset/Image.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/AppImage/IconForAllLookingView/Contents.json
  BudgetBuddies/BudgetBuddies/Sources/Extensions/UITextField+.swift
  BudgetBuddies/BudgetBuddies/Sources/Extensions/UITextView+.swift
  BudgetBuddies/BudgetBuddies/Sources/Extensions/UIView+.swift
  BudgetBuddies/BudgetBuddies/Sources/RootTabBarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/Consume/ConsumeViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryHeaderView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryTableViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistory/ConsumedHistoryView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistoryDetail/ConsumedHistoryDetailView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/ConsumedHistoryDetail/ConsumedHistoryDetailViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllServiceContainerView/AllServiceContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AnalysisContainerView/AnalysisContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/ProflieContainerView/ProfileContainerView.swift
Labels: feature

#39 [Feat] ProfileEditView UI 구현 #38
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingView/AllLookingView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingView/AllServiceContainerView/AllServiceContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingView/AnalysisContainerView/AnalysisContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingView/ProflieContainerView/ProfileContainerView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/AllLookingViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/SubView/ProfileEditView.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AllLooking/SubView/ProfileEditViewController.swift
Labels: feature

#41 [Refactor] CategoryEditView에 있는 카테고리 아이콘을 디자인 이미지로 변경 #40
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/PersonalCategoryImage.imageset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/PersonalCategoryImage.imageset/Image.png
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategoryPlus/CategoryPlus.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/CategorySelectTableViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/AccountBook/CategorySelect/DefaultCategory.swift
Labels: refactor

#43 Splash Screen 제작
  BudgetBuddies/BudgetBuddies/Resources/Base.lproj/LaunchScreen.storyboard
Labels: feature

#44 [Feat] 캘린더 UI 구현
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/nextButtonImage.imageset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/nextButtonImage.imageset/Image.png
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/prevButtonImage.imageset/Contents.json
  BudgetBuddies/BudgetBuddies/Resources/Assets.xcassets/prevButtonImage.imageset/Image.png
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/BottomSheet/Controllers/BottomSheetViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/BottomSheet/Views/BottomSheet.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Controllers/CalendarViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/CustomDayLabel.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/CustomInfoColor.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/InformationCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/Calendar/Views/MainCalendarCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/InfoList/Controllers/InfoListViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/MonthPicker/Controllers/MonthPickerViewController.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/MonthPicker/Views/MonthCell.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/MonthPicker/Views/MonthPicker.swift
  BudgetBuddies/BudgetBuddies/Sources/Screen/Calendar/TempModel.swift
Labels: feature, refactor
